title: Settings
fields:
  -
    handle: page_class
    field:
      options:
        page-privacy: Datenschutz
        page-imprint: Impressum
        page-team: Team
        page-shop: Shop
      type: select
      display: 'Seiten CSS-Klasse'
      clearable: true
  -
    handle: debug
    field:
      type: toggle
      display: Debug
  -
    handle: template
    field:
      type: template
      display: Template
  -
    handle: layout
    field:
      type: template
      display: Layout
